version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /mnt/videos:/app/exports
    user: thekid
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=bereal.server
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /mnt/videos:/app/exports
    user: thekid
    command: celery -A bereal.celery worker --loglevel=INFO --logfile=celery.log -E
    environment:
      - FLASK_APP=bereal.server
    depends_on:
      - web
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
