version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    volumes:
      - ./exports:/app/exports
      - ./content:/app/content
    user: thekid
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=bereal.server
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    volumes:
      - ./exports:/app/exports
      - ./content:/app/content
    user: thekid
    command: celery -A bereal.celery worker --loglevel=INFO --logfile=celery.log -E
    environment:
      - FLASK_APP=bereal.server
    depends_on:
      - web
      - redis

  flower:
    build:
      context: .
      dockerfile: docker/Dockerfile.flower
    volumes:
      - ./exports:/app/exports
    user: thekid
    ports:
      - "5555:5555"
    command: celery -A bereal.celery flower --address=0.0.0.0 --inspect --enable-events --loglevel=DEBUG --logfile=flower.log
    environment:
      - FLASK_APP=bereal.server
    depends_on:
      - web
      - redis
      - celery

  redis:
    image: "redis:alpine"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
